language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28
    - extra-google-m2repository

script: "./gradlew assembledebug"
